src/Core.Web/Controllers/IdentidadeController.cs
using Core.Web.Extensions;
using Core.Web.Models;
using Core.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace Core.Web.Controllers
{
    public class IdentidadeController : MainController
    {
        private readonly IAutenticacaoService _autenticacaoService;
        private readonly IAspNetUser _aspNetUser;

        public IdentidadeController(IAutenticacaoService autenticacaoService, 
                                    IAspNetUser aspNetUser)
        {
            _autenticacaoService = autenticacaoService;
            _aspNetUser = aspNetUser;
        }

        [HttpGet]
        [Route("nova-conta")]
        public IActionResult Registro()
        {
            if (!_aspNetUser.PossuiRoleAdmin())
                return new StatusCodeResult(404);

            ViewData["SelectListRoles"] = new SelectList(_autenticacaoService.GetRoles(), "Name", "Name", null);

            return View();
        }

        [HttpPost]
        [Route("nova-conta")]
        public async Task<IActionResult> Registro(UsuarioRegistro usuarioRegistro)
        {
            if (!ModelState.IsValid) return View(usuarioRegistro);

            var resposta = await _autenticacaoService.Registro(usuarioRegistro);

            if (ResponsePossuiErros(resposta.ResponseResult))
            {
                ViewData["SelectListRoles"] = new SelectList(_autenticacaoService.GetRoles(), "Name", "Name", null);
                return View(usuarioRegistro);
            }

            await _autenticacaoService.RealizarLogin(resposta);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("login")]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login(UsuarioLogin usuarioLogin, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;

            if (!ModelState.IsValid) return View(usuarioLogin);

            var resposta = await _autenticacaoService.Login(usuarioLogin);

            if (ResponsePossuiErros(resposta.ResponseResult)) return View(usuarioLogin);

            await _autenticacaoService.RealizarLogin(resposta);

            if (string.IsNullOrEmpty(returnUrl)) return RedirectToAction("Index", "Home");

            return LocalRedirect(returnUrl);
        }

        [HttpGet]
        [Route("sair")]
        public async Task<IActionResult> Logout()
        {
            await _autenticacaoService.Logout();
            return RedirectToAction("Index", "Home");
        }
    }
}

src/Core.Web/Views/Identidade/Login.cshtml
@model Core.Web.Models.UsuarioLogin

@{
    ViewData["Title"] = "Login de usuário";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}


<section class="section-conten padding-y container" style="min-height:35vh">
    
    <vc:Summary></vc:Summary>

    <div class="login-box">


        <!-- /.login-logo -->
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <img src="https://www.lusodata.pt/wp-content/themes/pdm-lusodata/assets/images/logo-lusodata.svg" alt="Lusodata">
            </div>
            <div class="card-body">
                <h4 class="card-title mb-4">Seja bem vindo!</h4>
                <form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">

                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                        <input asp-for="Email" class="form-control" placeholder="Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                        <input type="password" asp-for="Password" class="form-control" placeholder="Password" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                    </div>
                </form>
            </div>            

            <!--<form action="../../index3.html" method="post">


                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                Remember Me
                            </label>
                        </div>
                    </div>-->
                    <!-- /.col -->
                    <!--<div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                    </div>-->
                    <!-- /.col -->
                <!--</div>
            </form>-->

            @*<div class="social-auth-links text-center mt-2 mb-3">
                <a href="#" class="btn btn-block btn-primary">
                    <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
                </a>
                <a href="#" class="btn btn-block btn-danger">
                    <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
                </a>
            </div>*@
            <!-- /.social-auth-links -->

            @*<p class="mb-1">
                <a href="forgot-password.html">I forgot my password</a>
            </p>*@
            @*<p class="mb-0">
                <a href="register.html" class="text-center">Register a new membership</a>
            </p>*@
        </div>
        <!-- /.card-body -->
    </div>

</section>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/Core.Web/Views/Identidade/Registro.cshtml
@model Core.Web.Models.UsuarioRegistro

@{
    ViewData["Title"] = "Registro de novo usuário";
    Layout = "~/Views/Shared/AdminLTE/_Layout.cshtml";
}

<section class="section-conten padding-y container" style="min-height: 35vh">
    
    <vc:Summary></vc:Summary>

    <div class="card mx-auto" style="max-width: 380px; margin-top: 100px;">

        <div class="card-body">
            <h4 class="card-title mb-4">Seja bem vindo!</h4>
            <br/>
            <br/>

            <form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">

                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input type="password" asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="ConfirmPassword"></label>
                    <input type="password" asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Role"></label>
                    <select asp-for="Role" class="form-control" asp-items="ViewBag.SelectListRoles">
                        <option value="">-- Selecione Perfil --</option>
                    </select>
                    <span asp-validation-for="Role" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Registrar</button>
                </div>
            </form>
        </div>
        @*<div class="card-footer text-center">Já tem uma conta?<a asp-controller="Identidade" asp-action="Login"> Entrar</a></div>*@
    </div>

</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}